// lib/reports.js - Fixed PDF generation
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

// Import autoTable properly
import autoTable from 'jspdf-autotable';

/**
 * Format currency
 */
export function formatCurrency(amount) {
  if (!amount) return 'ETB 0.00';
  return `ETB ${Number(amount).toFixed(2)}`;
}

/**
 * Format date for reports
 */
export function formatDate(date) {
  if (!date) return 'N/A';
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
}

/**
 * Check if there is data to export
 */
export function hasExportData(data) {
  return data && data.rows && data.rows.length > 0;
}

/**
 * Generate PDF Report - Fixed with proper autoTable
 */
export function generatePDFReport(data, options) {
  const { title, filename, columns, rows, summary } = options;
  
  // Validate data
  if (!columns || !rows || rows.length === 0) {
    console.warn('No data available for PDF export');
    throw new Error('No data available to export');
  }

  // Create PDF document
  const doc = new jsPDF('landscape', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Add header
  doc.setFontSize(18);
  doc.setTextColor(33, 33, 33);
  doc.text(title, pageWidth / 2, 20, { align: 'center' });
  
  // Add timestamp
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);
  
  // Add company name
  doc.setFontSize(12);
  doc.setTextColor(50, 50, 50);
  doc.text('Mikias Building Materials', pageWidth / 2, 37, { align: 'center' });
  
  // Add summary info
  let yPos = 45;
  if (summary && Object.keys(summary).length > 0) {
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    const summaryItems = [];
    if (summary.totalProducts !== undefined) summaryItems.push(`Products: ${summary.totalProducts}`);
    if (summary.totalCustomers !== undefined) summaryItems.push(`Customers: ${summary.totalCustomers}`);
    if (summary.totalQuotes !== undefined) summaryItems.push(`Total Quotes: ${summary.totalQuotes}`);
    if (summary.pending !== undefined) summaryItems.push(`Pending: ${summary.pending}`);
    if (summary.completed !== undefined) summaryItems.push(`Completed: ${summary.completed}`);
    if (summary.revenue !== undefined) summaryItems.push(`Revenue: ${formatCurrency(summary.revenue)}`);
    if (summary.inStock !== undefined) summaryItems.push(`In Stock: ${summary.inStock}`);
    if (summary.lowStock !== undefined) summaryItems.push(`Low Stock: ${summary.lowStock}`);
    if (summary.outOfStock !== undefined) summaryItems.push(`Out of Stock: ${summary.outOfStock}`);
    
    const summaryText = summaryItems.join(' | ');
    if (summaryText) {
      doc.text(summaryText, 14, yPos);
      yPos += 10;
    }
  }
  
  // Prepare table data - format values properly
  const tableColumn = columns.map(col => col.header);
  const tableRows = rows.map(row => columns.map(col => {
    let value = row[col.accessor];
    if (value === undefined || value === null) return '';
    
    // Format numbers
    if (typeof value === 'number') {
      if (col.accessor.includes('price') || col.accessor.includes('amount') || col.accessor.includes('revenue')) {
        return `ETB ${value.toFixed(2)}`;
      }
      return value;
    }
    if (typeof value === 'boolean') {
      return value ? 'Yes' : 'No';
    }
    return String(value);
  }));
  
  // Use autoTable with proper import
  try {
    // Method 1: Using autoTable as a function
    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: yPos,
      styles: {
        fontSize: 8,
        cellPadding: 2,
        overflow: 'linebreak',
      },
      headStyles: {
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontSize: 9,
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [240, 245, 250],
      },
      margin: { left: 14, right: 14 },
      tableWidth: 'auto',
      pageBreak: 'auto',
    });
    
    // Get the final Y position after the table
    const finalY = doc.lastAutoTable.finalY + 10;
    
    // Add footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Mikias Building Materials - Confidential`,
      pageWidth / 2,
      Math.min(finalY + 10, pageHeight - 10),
      { align: 'center' }
    );
    
    // Save PDF
    doc.save(`${filename}.pdf`);
    
  } catch (error) {
    console.error('Error generating PDF:', error);
    
    // Fallback: Create a simple PDF without table
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    const fallbackY = yPos + 20;
    doc.text('Report data is available. Please use Excel or CSV format for full data.', 14, fallbackY);
    doc.text(`Total Records: ${rows.length}`, 14, fallbackY + 10);
    
    // Save PDF
    doc.save(`${filename}.pdf`);
  }
}

/**
 * Generate Excel Report
 */
export function generateExcelReport(data, options) {
  const { title, filename, columns, rows, summary } = options;
  
  if (!columns || !rows || rows.length === 0) {
    console.warn('No data available for Excel export');
    throw new Error('No data available to export');
  }

  const wb = XLSX.utils.book_new();
  
  // Add summary sheet
  if (summary && Object.keys(summary).length > 0) {
    const summaryData = [
      ['Report Summary'],
      ['Generated:', new Date().toLocaleString()],
      [''],
      ['Metric', 'Value'],
    ];
    
    Object.entries(summary).forEach(([key, value]) => {
      const label = key.replace(/([A-Z])/g, ' $1').trim();
      let displayValue = value;
      if (typeof value === 'number' && (key.includes('revenue') || key.includes('Revenue'))) {
        displayValue = formatCurrency(value);
      } else if (typeof value === 'number' && key.includes('rate')) {
        displayValue = `${value}%`;
      }
      summaryData.push([label, displayValue]);
    });
    
    const summaryWs = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary');
  }
  
  // Create data sheet
  const headerRow = columns.map(col => col.header);
  const dataRows = rows.map(row => columns.map(col => {
    let value = row[col.accessor];
    if (value === undefined || value === null) return '';
    if (typeof value === 'number' && (col.accessor.includes('price') || col.accessor.includes('amount'))) {
      return Number(value.toFixed(2));
    }
    if (typeof value === 'boolean') {
      return value ? 'Yes' : 'No';
    }
    return value;
  }));
  const wsData = [headerRow, ...dataRows];
  const ws = XLSX.utils.aoa_to_sheet(wsData);
  
  // Auto column widths
  const colWidths = columns.map((col, index) => {
    const maxLength = Math.max(
      col.header.length,
      ...rows.map(row => String(row[col.accessor] || '').length)
    );
    return { wch: Math.min(Math.max(maxLength + 2, 15), 50) };
  });
  ws['!cols'] = colWidths;
  
  XLSX.utils.book_append_sheet(wb, ws, title.slice(0, 31));
  
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  saveAs(blob, `${filename}.xlsx`);
}

/**
 * Generate CSV Report
 */
export function generateCSVReport(data, options) {
  const { filename, columns, rows } = options;
  
  if (!columns || !rows || rows.length === 0) {
    console.warn('No data available for CSV export');
    throw new Error('No data available to export');
  }

  const headerRow = columns.map(col => col.header).join(',');
  const dataRows = rows.map(row => 
    columns.map(col => {
      let val = row[col.accessor];
      if (val === undefined || val === null) val = '';
      if (typeof val === 'boolean') {
        val = val ? 'Yes' : 'No';
      }
      if (typeof val === 'number' && (col.accessor.includes('price') || col.accessor.includes('amount'))) {
        val = val.toFixed(2);
      }
      const strVal = String(val);
      if (strVal.includes(',') || strVal.includes('"') || strVal.includes('\n')) {
        return `"${strVal.replace(/"/g, '""')}"`;
      }
      return strVal;
    }).join(',')
  );
  
  const csvContent = [headerRow, ...dataRows].join('\n');
  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  saveAs(blob, `${filename}.csv`);
}

/**
 * Export report based on format
 */
export function exportReport(data, options) {
  const { format, ...rest } = options;
  
  if (!data || !data.rows || data.rows.length === 0) {
    return {
      success: false,
      message: 'No data available to export. Please adjust your filters or try again.'
    };
  }

  try {
    switch (format) {
      case 'pdf':
        generatePDFReport(data, rest);
        break;
      case 'excel':
        generateExcelReport(data, rest);
        break;
      case 'csv':
        generateCSVReport(data, rest);
        break;
      default:
        throw new Error(`Unsupported format: ${format}`);
    }
    return { success: true };
  } catch (error) {
    console.error(`Error exporting to ${format}:`, error);
    throw error;
  }
}